version: '3.8'

services:
  laboratorio-ids:
    build: .
    container_name: tcc-jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      # Mapeia a pasta atual da sua máquina para a pasta /app do contêiner.
      # Isso garante que os notebooks e dados gerados não sejam perdidos se o contêiner for desligado.
      - .:/app